openapi: 3.0.3
info:
  title: Favourite Receipes
  description: 'The openapi describing each endpoint from favourite recipes APIs.'
  contact:
    email: andremadureira1993@gmail.com
  version: v3
servers:
  - url: http://localhost:8080/api/
    description: Localhost environment.

paths:
  /signin:
    get:
      tags:
        - Login
      summary: Login into the application
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        

components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        Authenticate:
          schema:
            type: string